#include <MDSplusException.hpp>

#include <mdsshr.h>

namespace mdsplus {

MDSplusException::MDSplusException()
    : std::runtime_error("Unknown Status Code")
{ }

MDSplusException::MDSplusException(int status)
    : std::runtime_error(MdsGetMsg(status))
    , _status(status)
{ }

void throwException(int status)
{
    switch (status)
    {
    case MDSplusWARNING:
        throw MDSplusWarning();
    case MDSplusERROR:
        throw MDSplusError();
    case MDSplusFATAL:
        throw MDSplusFatal();
    case MDSplusSANDBOX:
        throw MDSplusSandbox();
    case LibINSVIRMEM:
        throw LibInsufficientVirtualMemory();
    case LibINVSTRDES:
        throw LibInvalidStringDescriptor();
    case LibINVARG:
        throw LibInvalidArgument();
    case LibNOTFOU:
        throw LibNotFound();
    case LibQUEWASEMP:
        throw LibQueueEmpty();
    case LibKEYNOTFOU:
        throw LibKeyNotFound();
    case StrSTRTOOLON:
        throw StrStringTooLong();
    case StrNOMATCH:
        throw StrNoMatch();
    case StrINVDELIM:
        throw StrInvalidDelimiter();
    case StrNOELEM:
        throw StrNoElement();
    case TclFAILED_ESSENTIAL:
        throw TclFailedEssential();
    case TclNO_DISPATCH_TABLE:
        throw TclNoDispatchTable();
    case CamDONE_NOX:
        throw CamDoneNoX();
    case CamSERTRAERR:
        throw CamSerialTransmissionError();
    case CamSCCFAIL:
        throw CamSerialCrateControllerFailure();
    case CamOFFLINE:
        throw CamOffline();
    case MdsdclERROR:
        throw MdsdclError();
    case MdsdclIVVERB:
        throw MdsdclInvalidVerb();
    case MdsdclABSENT:
        throw MdsdclAbsent();
    case MdsdclNEGATED:
        throw MdsdclNegated();
    case MdsdclNOTNEGATABLE:
        throw MdsdclNotNegatable();
    case MdsdclIVQUAL:
        throw MdsdclInvalidQualifier();
    case MdsdclPROMPT_MORE:
        throw MdsdclPromptMore();
    case MdsdclTOO_MANY_PRMS:
        throw MdsdclTooManyParameters();
    case MdsdclTOO_MANY_VALS:
        throw MdsdclTooManyValues();
    case MdsdclMISSING_VALUE:
        throw MdsdclMissingValue();
    case TreeNMN:
        throw TreeNoMoreNodes();
    case TreeNMT:
        throw TreeNoMoreTags();
    case TreeNNF:
        throw TreeNodeNotFound();
    case TreeTNF:
        throw TreeTagNotFound();
    case TreeTREENF:
        throw TreeNotFound();
    case TreeALREADY_THERE:
        throw TreeNodeAlreadyThere();
    case TreePARENT_OFF:
        throw TreeParentOff();
    case TreeBOTH_OFF:
        throw TreeNodeAndParentOff();
    case TreeOFF:
        throw TreeNodeIsOff();
    case TreeNOT_OPEN:
        throw TreeNotOpen();
    case TreeNOMETHOD:
        throw TreeNoMethod();
    case TreeBADRECORD:
        throw TreeBadRecord();
    case TreeINVTREE:
        throw TreeInvalidTreeStructure();
    case TreeDUPTAG:
        throw TreeDuplicateTag();
    case TreeILLPAGCNT:
        throw TreeIllegalPageCount();
    case TreeMAXOPENEDIT:
        throw TreeMaxOpenForEdit();
    case TreeNODATA:
        throw TreeNoData();
    case TreeNOEDIT:
        throw TreeNotOpenForEdit();
    case TreeNOTCHILDLESS:
        throw TreeNodeHasChildren();
    case TreeINVPATH:
        throw TreeInvalidPath();
    case TreeILLEGAL_ITEM:
        throw TreeIllegalItem();
    case TreeBUFFEROVF:
        throw TreeBufferOverflow();
    case TreeUNSPRTCLASS:
        throw TreeUnsupportedClass();
    case TreeCONGLOMFULL:
        throw TreeConglomFull();
    case TreeCONGLOM_NOT_FULL:
        throw TreeConglomNotFull();
    case TreeUNRESOLVED:
        throw TreeUnresolved();
    case TreeINVDFFCLASS:
        throw TreeInvalidDataFormatClass();
    case TreeINVRECTYP:
        throw TreeInvalidRecordType();
    case TreeNODNAMLEN:
        throw TreeNodeNameTooLong();
    case TreeTAGNAMLEN:
        throw TreeTagNameTooLong();
    case TreeWRITEFIRST:
        throw TreeNeedWriteFirst();
    case TreeNOT_CONGLOM:
        throw TreeNotConglom();
    case TreeUNSUPARRDTYPE:
        throw TreeUnsupportedArrayType();
    case TreeNOTMEMBERLESS:
        throw TreeNodeHasMembers();
    case TreeNOTSON:
        throw TreeInvalidSubtreeNode();
    case TreeNOOVERWRITE:
        throw TreeNodeWriteOnce();
    case TreeINVDTPUSG:
        throw TreeInvalidPutUsage();
    case TreeEDITING:
        throw TreeNotPermittedWhileEditing();
    case TreeNOWRITEMODEL:
        throw TreeNoWriteModel();
    case TreeNOWRITESHOT:
        throw TreeNoWriteShot();
    case TreeNOLOG:
        throw TreeNoPathDefined();
    case TreeREADONLY:
        throw TreeReadOnly();
    case TreeREADERR:
        throw TreeRecordReadError();
    case TreeNOT_IN_LIST:
        throw TreeNotInList();
    case TreeCANCEL:
        throw TreeCancel();
    case TreeUNSUPTHICKOP:
        throw TreeUnsupportedThickOperation();
    case TreeFAILURE:
        throw TreeFailure();
    case TreeFILE_NOT_FOUND:
        throw TreeFileNotFound();
    case TreeLOCK_FAILURE:
        throw TreeLockFailure();
    case TreeNOSEGMENTS:
        throw TreeNoSegments();
    case TreeINVDTYPE:
        throw TreeInvalidSegmentDataType();
    case TreeINVSHAPE:
        throw TreeInvalidSegmentShape();
    case TreeINVSHOT:
        throw TreeInvalidShot();
    case TreeINVTAG:
        throw TreeInvalidTag();
    case TreeNOPATH:
        throw TreeNoPath();
    case TreeTREEFILEREADERR:
        throw TreeTreeFileReadError();
    case TreeMEMERR:
        throw TreeMemoryAllocateError();
    case TreeNOCURRENT:
        throw TreeNoCurrentShot();
    case TreeFOPENW:
        throw TreeOpenReadWriteFailed();
    case TreeFOPENR:
        throw TreeOpenReadOnlyFailed();
    case TreeFCREATE:
        throw TreeCreateFailed();
    case TreeCONNECTFAIL:
        throw TreeConnectFailed();
    case TreeNCIWRITE:
        throw TreeNCIWriteError();
    case TreeDELFAIL:
        throw TreeDeleteFailed();
    case TreeRENFAIL:
        throw TreeRenameFailed();
    case TreeEMPTY:
        throw TreeEmpty();
    case TreePARSEERR:
        throw TreeParseError();
    case TreeNCIREAD:
        throw TreeNCIReadError();
    case TreeNOVERSION:
        throw TreeNoVersion();
    case TreeDFREAD:
        throw TreeDatafileReadError();
    case TreeCLOSEERR:
        throw TreeFileCloseError();
    case TreeMOVEERROR:
        throw TreeFileOverwriteError();
    case TreeOPENEDITERR:
        throw TreeOpenFileForEditError();
    case TreeREADONLY_TREE:
        throw TreeOpenReadOnly();
    case TreeWRITETREEERR:
        throw TreeWriteTreeFileError();
    case TreeNOWILD:
        throw TreeWildcardInNodeSpecifier();
    case TdiBREAK:
        throw TdiMissingBreak();
    case TdiCASE:
        throw TdiMissingCase();
    case TdiCONTINUE:
        throw TdiMissingContinue();
    case TdiEXTRANEOUS:
        throw TdiExtraneousCharacters();
    case TdiRETURN:
        throw TdiExtraneousReturn();
    case TdiABORT:
        throw TdiAbort();
    case TdiBAD_INDEX:
        throw TdiBadIndex();
    case TdiBOMB:
        throw TdiBadPunctuation();
    case TdiEXTRA_ARG:
        throw TdiTooManyArguments();
    case TdiGOTO:
        throw TdiMissingGotoLabel();
    case TdiINVCLADSC:
        throw TdiInvalidClass();
    case TdiINVCLADTY:
        throw TdiInvalidClassForDataType();
    case TdiINVDTYDSC:
        throw TdiInvalidDataType();
    case TdiINV_OPC:
        throw TdiInvalidOpcode();
    case TdiINV_SIZE:
        throw TdiInvalidSize();
    case TdiMISMATCH:
        throw TdiArgumentMismatch();
    case TdiMISS_ARG:
        throw TdiMissingArgument();
    case TdiNDIM_OVER:
        throw TdiTooManyDimensions();
    case TdiNO_CMPLX:
        throw TdiComplexUnsupported();
    case TdiNO_OPC:
        throw TdiOpcodeUnsupported();
    case TdiNO_OUTPTR:
        throw TdiNoOutputPointer();
    case TdiNO_SELF_PTR:
        throw TdiNoSelfPointer();
    case TdiNOT_NUMBER:
        throw TdiNotANumber();
    case TdiNULL_PTR:
        throw TdiNullPointer();
    case TdiRECURSIVE:
        throw TdiRecursionLimitReached();
    case TdiSIG_DIM:
        throw TdiSignalDimensionMismatch();
    case TdiSYNTAX:
        throw TdiSyntaxError();
    case TdiTOO_BIG:
        throw TdiPrecisionLoss();
    case TdiUNBALANCE:
        throw TdiUnbalanced();
    case TdiUNKNOWN_VAR:
        throw TdiUnknownVariable();
    case TdiSTRTOOLON:
        throw TdiStringTooLong();
    case TdiTIMEOUT:
        throw TdiTimeout();
    case ApdAPD_APPEND:
        throw ApdAppendError();
    case ApdDICT_KEYVALPAIR:
        throw ApdInvalidKeyValuePair();
    case ApdDICT_KEYCLS:
        throw ApdKeyNotScalar();
    case ServerNOT_DISPATCHED:
        throw ServerNotDispatched();
    case ServerINVALID_DEPENDENCY:
        throw ServerInvalidDependency();
    case ServerCANT_HAPPEN:
        throw ServerCantHappen();
    case ServerINVSHOT:
        throw ServerInvalidShot();
    case ServerABORT:
        throw ServerAborted();
    case ServerPATH_DOWN:
        throw ServerPathDown();
    case ServerSOCKET_ADDR_ERROR:
        throw ServerSocketAddressError();
    case ServerINVALID_ACTION_OPERATION:
        throw ServerInvalidActionOperation();
    case DevBAD_ENDIDX:
        throw DevBadEndIndex();
    case DevBAD_FILTER:
        throw DevBadFilter();
    case DevBAD_FREQ:
        throw DevBadFrequency();
    case DevBAD_GAIN:
        throw DevBadGain();
    case DevBAD_HEADER:
        throw DevBadHeader();
    case DevBAD_HEADER_IDX:
        throw DevBadHeaderIndex();
    case DevBAD_MEMORIES:
        throw DevBadMemories();
    case DevBAD_MODE:
        throw DevBadMode();
    case DevBAD_NAME:
        throw DevBadName();
    case DevBAD_OFFSET:
        throw DevBadOffset();
    case DevBAD_STARTIDX:
        throw DevBadStartIndex();
    case DevNOT_TRIGGERED:
        throw DevNotTriggered();
    case DevFREQ_TOO_HIGH:
        throw DevFrequencyTooHigh();
    case DevINVALID_NOC:
        throw DevInvalidNumberOfChannels();
    case DevRANGE_MISMATCH:
        throw DevRangeMismatch();
    case DevCAMACERR:
        throw DevCAMACIOError();
    case DevBAD_VERBS:
        throw DevBadVerbs();
    case DevBAD_COMMANDS:
        throw DevBadCommands();
    case DevCAM_ADNR:
        throw DevCAMACAdressNotRecognized();
    case DevCAM_ERR:
        throw DevCAMACError();
    case DevCAM_LOSYNC:
        throw DevCAMACLostSyncError();
    case DevCAM_LPE:
        throw DevCAMACLongitudinalParityError();
    case DevCAM_TMO:
        throw DevCAMACHighwayTimeoutError();
    case DevCAM_TPE:
        throw DevCAMACTransverseParityError();
    case DevCAM_STE:
        throw DevCAMACSerialTransmissionError();
    case DevCAM_DERR:
        throw DevCAMACDerr();
    case DevCAM_SQ:
        throw DevCAMACDoneQ();
    case DevCAM_NOSQ:
        throw DevCAMACDoneNoQ();
    case DevCAM_SX:
        throw DevCAMACDoneX();
    case DevCAM_NOSX:
        throw DevCAMACDoneNoX();
    case DevINV_SETUP:
        throw DevInvalidSetup();
    case DevPYDEVICE_NOT_FOUND:
        throw DevPyDeviceNotFound();
    case DevPY_INTERFACE_LIBRARY_NOT_FOUND:
        throw DevPyInterfaceLibraryNotFound();
    case DevIO_STUCK:
        throw DevIOStuck();
    case DevUNKNOWN_STATE:
        throw DevUnknownState();
    case DevWRONG_TREE:
        throw DevWrongTree();
    case DevWRONG_PATH:
        throw DevWrongPath();
    case DevWRONG_SHOT:
        throw DevWrongShot();
    case DevOFFLINE:
        throw DevOffline();
    case DevTRIGGERED_NOT_STORED:
        throw DevTriggeredNotStored();
    case DevNO_NAME_SPECIFIED:
        throw DevNoNameSpecified();
    case DevBAD_ACTIVE_CHAN:
        throw DevBadActiveChannel();
    case DevBAD_TRIG_SRC:
        throw DevBadTriggerSource();
    case DevBAD_CLOCK_SRC:
        throw DevBadClockSource();
    case DevBAD_PRE_TRIG:
        throw DevBadPreTrigger();
    case DevBAD_POST_TRIG:
        throw DevBadPostTrigger();
    case DevBAD_CLOCK_FREQ:
        throw DevBadClockFrequency();
    case DevTRIGGER_FAILED:
        throw DevTriggerFailed();
    case DevERROR_READING_CHANNEL:
        throw DevErrorReadingChannel();
    case DevERROR_DOING_INIT:
        throw DevErrorDoingInit();
    case DevCANNOT_LOAD_SETTINGS:
        throw DevCannotLoadSettings();
    case DevCANNOT_GET_BOARD_STATE:
        throw DevCannotGetBoardState();
    case DevBAD_PARAMETER:
        throw DevBadParameter();
    case DevCOMM_ERROR:
        throw DevCommunicationError();
    case DevCAMERA_NOT_FOUND:
        throw DevCameraNotFound();
    case DevNOT_A_PYDEVICE:
        throw DevNotAPyDevice();
    }
}

} // namespace mdsplus
